parameters:
- name: platforms
  type: object
  default:
  - vs
  - barefoot
  - broadcom
  - mellanox
  - centec-arm64
  - centec
  - marvell-armhf
  - generic

jobs:
- job: Build
  pool: sonic-mirror-westus2-2
  timeoutInMinutes: 120
  variables:
  - group: Debian-Mirror-Common
  steps:
  - checkout: self
    clean: true
  - ${{ each platform in parameters.platforms }}:
    - task: DownloadPipelineArtifact@2
      displayName: Download ${{ platform }} versions-docker
      continueOnError: true 
      inputs:
        source: specific
        project: build
        pipeline: Azure.sonic-buildimage.official.${{ platform }}
        runVersion: 'latestFromBranch'
        runBranch: '$(Build.SourceBranch)'
        path: download
        patterns: |
          **/target/versions/default/versions-docker
  - script: |
      set -ex
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      sudo systemctl start docker
      az login -u $(ApplicationId) --service-principal --tenant $(AzureTenant) -p "$ApplicationKey"
      images=$(find download -name versions-docker | xargs -i grep -v "==$" {} | awk -F== '{print$1}' | sort -u | sed -e "s/amd64://" -e "s/arm64://" -e "s/armhf://" | sort -u )
      for i in $images
      do
        docker pull $i | grep Digest
        az acr import -n PublicMirror --source docker.io/$i --image $i --force
      done
    env:
      ApplicationKey: '$(ApplicationKey)'
